# SD212: Graph mining

# Lab 1: Sparse matrices

The objective of this lab is to understand the structure and main properties of [sparse matrices](https://en.wikipedia.org/wiki/Sparse_matrix).

## Import

In [1]:
import numpy as np

In [2]:
from scipy import sparse

## Coordinate format

In [3]:
# random matrix (dense format)
A_dense = np.random.randint(2, size = (5,10))

In [4]:
A_dense

array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 0]])

In [5]:
A_coo = sparse.coo_matrix(A_dense)

In [6]:
A_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in COOrdinate format>

In [7]:
A_coo.shape

(5, 10)

In [8]:
A_coo.nnz

17

In [9]:
print(A_coo.row)
print(A_coo.col)
print(A_coo.data)

[0 0 0 0 1 1 1 2 3 3 3 3 4 4 4 4 4]
[2 4 5 9 1 2 9 6 0 1 2 7 1 3 5 7 8]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [10]:
row = A_coo.row
col = A_coo.col
data = np.random.randint(10, size=len(A_coo.data))
shape = A_coo.shape

In [11]:
B_coo = sparse.coo_matrix((data, (row, col)), shape)

In [12]:
B_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in COOrdinate format>

In [13]:
B_coo.toarray()

array([[0, 0, 8, 0, 9, 7, 0, 0, 0, 7],
       [0, 8, 9, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 7, 0, 0, 0],
       [2, 6, 8, 0, 0, 0, 0, 6, 0, 0],
       [0, 5, 0, 2, 0, 6, 0, 7, 0, 0]])

In [14]:
B_coo.nnz

17

In [15]:
np.sum(B_coo.data > 0)

16

In [16]:
B_coo.eliminate_zeros()

In [17]:
B_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in COOrdinate format>

## To do

Complete the function below that converts a dense matrix into a sparse matrix in COO format. 

Needless to say...
* don't use `scipy`
* don't use any loop

In [20]:
class SparseCOO():
    def __init__(self, data: np.ndarray = None, row: np.ndarray = None, 
                 col: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.row = row
        self.col = col
        self.shape = shape

In [244]:
def dense_to_coo(A):
    '''Convert dense matrix to sparse in COO format.
    
    Parameters
    ----------
    A : np.ndarray
        Dense matrix
        
    Returns
    -------
    A_coo : SparseCOO
        Sparse matrix in COO format.
    '''
    # to be modified
    
    data = A[A!=0]
    index = np.argwhere(A != 0)
    row = index[:,0]
    col = index[:,1]
    shape = A.shape
    sparseCOO = SparseCOO(data, row, col,shape)
    return sparseCOO

In [49]:
sparseCOO = dense_to_coo(A_dense)
print(sparseCOO.data)
print(sparseCOO.row)
print(sparseCOO.col)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 1 1 1 2 3 3 3 3 4 4 4 4 4]
[2 4 5 9 1 2 9 6 0 1 2 7 1 3 5 7 8]


## CSR format

The CSR (Compressed Sparse Row) format is the more efficient for arithmetic operations (see below).

In [25]:
A_dense

array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 0]])

In [26]:
A_csr = sparse.csr_matrix(A_dense)

In [27]:
A_csr

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [28]:
A_csr.shape

(5, 10)

In [29]:
A_csr.nnz

17

In [30]:
print(A_csr.indices)
print(A_csr.indptr)
print(A_csr.data)

[2 4 5 9 1 2 9 6 0 1 2 7 1 3 5 7 8]
[ 0  4  7  8 12 17]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [31]:
A_csr[3, 4]

0

In [32]:
A_csr[3]

<1x10 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [33]:
indices = A_csr.indices
indptr = A_csr.indptr
data = np.random.randint(10, size=len(A_csr.data))
shape = A_csr.shape

In [34]:
B_csr = sparse.csr_matrix((data, indices, indptr), shape)

In [35]:
B_csr

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [36]:
B_csr.eliminate_zeros()

In [37]:
B_csr

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [38]:
# from COO format
row = [0, 0, 1, 2, 2]
col = [2, 3, 0, 1, 2]
data = np.ones(5)
A_csr = sparse.csr_matrix((data, (row, col)), shape = (3, 4))

In [39]:
A_csr.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

In [40]:
# equivalently
A_coo = sparse.coo_matrix((data, (row, col)), shape = (3, 4))
A_csr = sparse.csr_matrix(A_coo)

In [41]:
A_csr.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

## To do

Complete the functions below that converts:
* a dense matrix into a sparse matrix in CSR format,
* a sparse matrix in COO format to CSR format.

Again...
* don't use `scipy`
* don't use any loop

In [141]:
class SparseCSR():
    def __init__(self, data: np.ndarray = None, indices: np.ndarray = None, 
                 indptr: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape

In [142]:
def dense_to_csr(A):
    '''Convert dense matrix to sparse in CSR format.
    
    Parameters
    ----------
    A : np.ndarray
        Dense matrix
        
    Returns
    -------
    A_csr : SparseCSR
        Sparse matrix in CSR format.
    '''
    # to be modified
    sparseCOO = dense_to_coo(A)
    sparseCSR = coo_to_csr(sparseCOO)
    return sparseCSR

In [245]:
def coo_to_csr(A_coo):
    '''Convert a sparse matrix from COO to CSR format.
    
    Parameters
    ----------
    A_coo : SparseCSR
        Sparse matrix in COO format.
        
    Returns
    -------
    A_csr : SparseCSR
        Sparse matrix in CSR format.
    '''
    # to be modified
    
    shape = A_coo.shape
    data = A_coo.data
    indices = A_coo.col
    B, C = np.unique(A_coo.row, return_counts=True)
    diff = np.diff(B)
    min_row = np.sort(B)[0]
    if (min_row > 0):
        C = np.insert(C, 2*min_row*[0], [i for i in range(min_row)])
    else: 
        C = np.insert(C,0,0)
        
    index = np.argwhere(diff[diff>1]).ravel()
    if (index.size != 0):
        C = np.insert(C, index, C[index])
    
    indptr = np.cumsum(C)
    
    sparseCSR = SparseCSR(data, indices, indptr, shape)
    return sparseCSR

In [219]:
sparseCSR = dense_to_csr(A_dense)
print(sparseCSR.data)
print(sparseCSR.indices)
print(sparseCSR.indptr)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[2 4 5 9 1 2 9 6 0 1 2 7 1 3 5 7 8]
[ 0  4  7  8 12 17]


## CSC format

In [71]:
A_dense

array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 0]])

In [72]:
A_csc = sparse.csc_matrix(A_dense)

In [73]:
A_csc

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Column format>

In [74]:
A_csc.shape

(5, 10)

In [75]:
A_csc.nnz

17

In [76]:
print(A_csc.indices)
print(A_csc.indptr)
print(A_csc.data)

[3 1 3 4 0 1 3 4 0 0 4 2 3 4 4 0 1]
[ 0  1  4  7  8  9 11 12 14 15 17]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## LIL format

In [77]:
A_dense

array([[0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 0]])

In [78]:
A_lil = sparse.lil_matrix(A_dense)

In [79]:
A_lil

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in List of Lists format>

In [80]:
print(A_lil.rows)
print(A_lil.data)

[list([2, 4, 5, 9]) list([1, 2, 9]) list([6]) list([0, 1, 2, 7])
 list([1, 3, 5, 7, 8])]
[list([1, 1, 1, 1]) list([1, 1, 1]) list([1]) list([1, 1, 1, 1])
 list([1, 1, 1, 1, 1])]


In [81]:
A_lil = sparse.lil_matrix(A_csr)

## To do

What is the best format to modify an entry to a sparse matrix?

**The best format to modify an entry to a sparse matrix is a list of list.**

In [82]:
A_csr[0, 2] = 1

In [83]:
A_lil[0, 2] = 1

In [85]:
print(A_csr)

  (0, 2)	1.0
  (0, 3)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (2, 2)	1.0
  (0, 2)	1.0
  (0, 3)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (2, 2)	1.0


In [86]:
print(A_lil)

  (0, 2)	1.0
  (0, 3)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (2, 2)	1.0


## Diagonal format

In [87]:
A_diag = sparse.diags(np.arange(5))

In [88]:
A_diag

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements (1 diagonals) in DIAgonal format>

In [89]:
A_diag.toarray()

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

In [90]:
A_diag.diagonal()

array([0., 1., 2., 3., 4.])

In [91]:
A = sparse.csr_matrix(A_diag)

In [92]:
A

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

## To do

Complete the following function that returns a sparse CSR matrix with the pseudo-inverse vector on the diagonal.

**Example:** pseudo inverse of (0, 1, 2) -> (0, 1, 1/2)

**Hint:** Use the property of sparse matrices!

In [220]:
def pseudo_inverse(vector):
    '''Return a sparse matrix with pseudo-inverse on the diagonal.
    
    Parameters
    ----------
    vector : np.ndarray
        Input vector. 
        
    Returns
    -------
    A_csr : sparse.csr_matrix
        Sparse matrix in scipy CSR format.
    '''    
    # to be modified
    
    A = dense_to_csr(vector)
    data = A.data.astype(float)
    indices = A.indices
    indptr = A.indptr
    count = 0
    
    for i in indptr[:-1]:
        j = indices[i]
        if (j == count):
            data[i] = 1/data[i]
        count = count + 1
    sparseCSR = SparseCSR(data, indices, indptr)
    return sparseCSR

In [222]:
A_ex = np.array(A_diag.toarray())
sparseCSR_diag = pseudo_inverse(A_ex)
print(sparseCSR_diag.data)
print(sparseCSR_diag.indices)
print(sparseCSR_diag.indptr)

[1.         0.5        0.33333333 0.25      ]
[1 2 3 4]
[0 0 1 2 3 4]


## Operations

Usual arithmetic operations apply to sparse matrices. The only contraint is to have a sparse matrix on the **left-hand side** of the operator.

In [223]:
A = sparse.csr_matrix(A_dense)

In [224]:
n_row, n_col = A.shape

In [225]:
A.dot(np.ones(n_col, dtype=int))

array([4, 3, 1, 4, 5], dtype=int64)

In [226]:
A.T.dot(np.ones(n_row, dtype=int))

array([1, 3, 3, 1, 1, 2, 1, 2, 1, 2], dtype=int64)

In [227]:
# observe the format of the transpose
A.T

<10x5 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Column format>

In [228]:
A.T.dot(A)

<10x10 sparse matrix of type '<class 'numpy.int64'>'
	with 54 stored elements in Compressed Sparse Column format>

In [229]:
A.dot(A.T)

<5x5 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [230]:
A.data = np.random.choice((1,2,3,4), size = len(A.data))

In [231]:
B = A > 1

In [232]:
B

<5x10 sparse matrix of type '<class 'numpy.bool_'>'
	with 12 stored elements in Compressed Sparse Row format>

In [233]:
# Explain the following warning...
B = A < 1

/Users/eric/anaconda3/lib/python3.7/site-packages/scipy/sparse/compressed.py:287: SparseEfficiencyWarning: Comparing a sparse matrix with a scalar greater than zero using < is inefficient, try using >= instead.
  warn(bad_scalar_msg, SparseEfficiencyWarning)


In [234]:
B

<5x10 sparse matrix of type '<class 'numpy.bool_'>'
	with 33 stored elements in Compressed Sparse Row format>

In [235]:
B_dense = np.random.randint(2, size = (5,10))
B = sparse.csr_matrix(B_dense)

In [236]:
2 * A + 5 * B

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 26 stored elements in Compressed Sparse Row format>

## To do

* Complete the following function that normalizes a sparse CSR matrix with non-negative entries so that each row sums to 1 (or to 0 if the whole row is zero). 
* Do the same for the columns. 

In [237]:
def normalize_rows(A):
    '''Normalize the rows of a CSR matrix so that all sum to 1 (or 0).
    
    Parameters
    ----------
    A : sparse.csr_matrix
        Input matrix (non-negative entries).
    
    Returns
    -------
    X_ : sparse.csr_matrix
        Normalized matrix. 
    
    '''
    # to be modified
    data = A.data.astype(float)
    indices = A.indices
    indptr = A.indptr
    
    for i in range(indptr.shape[0]-1):
        s = 0
        for j in range(indptr[i], indptr[i+1]):
            s = s + data[j]
        for j in range(indptr[i], indptr[i+1]):
            data[j] = data[j]/s
    sparseCSR = SparseCSR(data, indices, indptr)
    return sparseCSR

In [243]:
print(A_dense)
print(normalize_rows(sparse.csr_matrix(A_dense)).data)

[[0 0 1 0 1 1 0 0 0 1]
 [0 1 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0]
 [1 1 1 0 0 0 0 1 0 0]
 [0 1 0 1 0 1 0 1 1 0]]
[0.25       0.25       0.25       0.25       0.33333333 0.33333333
 0.33333333 1.         0.25       0.25       0.25       0.25
 0.2        0.2        0.2        0.2        0.2       ]


## To do

Complete the following method that returns the dot product of a sparse CSR matrix with a vector.

* No loop allowed!

In [ ]:
class SparseCSR():
    def __init__(self, data: np.ndarray = None, indices: np.ndarray = None, 
                 indptr: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape
        
    def dot(self, x: np.ndarray) -> np.ndarray:
        '''Sparse-vector dot product.'''
        # to be modified
        data = self.data
        indices = self.indices
        indptr = self.indptr
        shape = self.shape
        
        
        
        return None

## Slicing

Sparse matrices can be sliced like numpy arrays. The CSR format is more efficient for row slicing (although column slicing is possible), while the CSC format is more efficient for column slicing.

In [ ]:
A = sparse.csr_matrix(A_dense)

In [ ]:
A[:2]

In [ ]:
A[1:4][:,2:]

In [ ]:
A[np.array([0,2,4])]

## To do 

Consider the following matrix:

In [ ]:
A = sparse.csr_matrix(np.random.randint(2, size = (20,30)))

* Extract the 10 rows of largest sums and build the corresponding matrix.

## Bonus

Complete all methods of the following CSR class.

In [ ]:
class SparseCSR():
    def __init__(self, data: np.ndarray = None, indices: np.ndarray = None, 
                 indptr: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape
        
    def dot(self, x: np.ndarray) -> np.ndarray:
        '''Sparse-vector dot product.'''
        # to be modified
        return None

    def dot_array(self, X: np.ndarray) -> np.ndarray:
        '''Sparse-array dot product.'''
        # to be modified
        return None
    
    def dot_sparse(self, X: SparseCSR) -> SparseCSR:
        '''Sparse-sparse dot product.'''
        # to be modified
        return None
    
    def add_sparse(self, X: SparseCSR) -> SparseCSR:
        '''Add a sparse matrix.'''
        # to be modified
        return None
    
    def slice_row(self, index: np.ndarray) -> SparseCSR:
        '''Slice rows of a sparse matrix.'''
        # to be modified
        return None
    
    def slice_col(self, index: np.ndarray) -> SparseCSR:
        '''Slice columns of a sparse matrix.'''
        # to be modified
        return None
    
    def eliminate_zeros(self) -> SparseCSR:
        '''Eliminate zeros of a sparse matrix.'''
        # to be modified
        return None